#!/bin/bash
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
   sudo apt-get update
   sudo apt-get install -qq curl
   sudo apt-get install openjdk-8-jdk
elif [[ "$unamestr" == 'OSX' ]]; then
   platform='OSX'
   ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
   brew update
   brew cask install java
fi
#ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#brew update
#brew cask install java
./VM/install-vm
