#!/bin/bash
cd /Users/colechristini/GitHub/Pod/Java\ pod\ template\ OSX/VM
curl -o alpine-minirootfs-3.6.2-x86_64.tar.gz http://dl-cdn.alpinelinux.org/alpine/v3.6/releases/x86_64/alpine-minirootfs-3.6.2-x86_64.tar.gz
sleep 20
cp /Users/colechristini/GitHub/Pod/Java\ pod\ template\ OSX/VM/alpine-minirootfs-3.6.2-x86_64.tar.gz /Users/colechristini/GitHub/Pod/Java\ pod\ template\ OSX/VM/filesystem
cd /Users/colechristini/GitHub/Pod/Java\ pod\ template\ OSX/VM/filesystem
gunzip alpine-minirootfs-3.6.2-x86_64.tar.gz
tar -xvf alpine-minirootfs-3.6.2-x86_64.tar
rm alpine-minirootfs-3.6.2-x86_64.tar

../libs/getlibs
